### ISSUE TITLE
unauthorized access returns an exception trace

### ISSUE THREAD

**Issue by ajoslin103** [MichielDeMey/express-jwt-permissions#5]
unauthorized access returns an exception trace

were/how do I change that to returning an HTML error 403 ?

UnauthorizedError: Permission denied
   at Object.<anonymous> (/path/to/my/dev/folder/node_modules/express-jwt-permissions/index.js:4:23)
   at Module._compile (module.js:556:32)
   at Object.Module._extensions..js (module.js:565:10)
   at Module.load (module.js:473:32)
   at tryModuleLoad (module.js:432:12)
   at Function.Module._load (module.js:424:3)
   at Function._load (/usr/local/lib/node_modules/pm2/node_modules/pmx/lib/transaction.js:62:21)
   at Module.require (module.js:483:17)
   at require (internal/module.js:20:19)
   at Object.<anonymous> (/path/to/my/dev/folder/index.js:11:49)

**Comment by ajoslin103** [comment]
never mind, I didn't understand that I had to plu my error handle _after_ the usages of guard()

**Comment by gillesdemey** [comment]
@ajoslin103 I agree that the documentation could have been more clear on this. I suggest we add an extra paragraph with an example of how to set this up with an error handling middleware. @michieldemey

**Comment by MichielDeMey** [comment]
Fixed in https://github.com/MichielDeMey/express-jwt-permissions/commit/2b713a9b009c37771779868f396a46fa51c62662.

We've added an error handling example to the README.

**Comment by ajoslin103** [comment]
this is still not working for me...

the sample error handling has guard used in a middleware .use style wheraas I am using it to protect each route individually

could you provide sample error handling for a per-route usage ?

**Comment by gillesdemey** [comment]
Exceptions thrown by the `guard` middleware will automatically propagate to the error handler since it calls `next(new UnauthorizedError())` internally.

This should work for your use-case:

```js
const requiresAdmin = guard.check('admin')

app.get('/admin', requiresAdmin, (req, res, next) => {
  ...
})

app.use((err, req, res) => {
  if (err.code === 'permission_denied') res.status(401).send('insufficient permissions')
})
```

**Comment by ajoslin103** [comment]
I am using it like this, and full stack dumps are being show in the error log

```
app.get('/event/:type', guard.check('event'), (req, res, next) => {
  ...
})

app.get('/force/:action', guard.check('force'), requiresAdmin, (req, res, next) => {
  ...
})

app.get('/status/:part', guard.check('status'), requiresAdmin, (req, res, next) => {
  ...
})

app.use((err, req, res) => {
  if (err.code === 'permission_denied') res.status(401).send('insufficient permissions')
})
```

**Comment by gillesdemey** [comment]
A couple of things to note:

1. The correct usage of the error handler is `app.use((err, req, res, next)`, this was incorrect in the README and has been fixed.
2. The `UnauthorizedError` can have codes other than `permission_denied` and so you shouldn't exclusively check for that one.

To prevent stackTraces from leaking you could have a generic exception handler that simply only returns the `message` or nothing at all.

ie.
```js
app.use((err, req, res, next) => {
  return res.status(401).send(err.message)
})
```

**Comment by ajoslin103** [comment]
gotcha!  this is working now -- although I changed that error handler a bit...

Thanks!

```
app.use((err, req, res, next) => {
	if (err) {
		return res.sendStatus(401,err.message);
	}
});
```
